title: VegDelicieus
email: info@linvirt.nl
description: >- 
  Website vol met de lekkerste vegan recepten
tagline: VegDelicieus | Een website met vegan recepten voor elke dag 
website: https://www.vegdelicieus.nl
author: Frederik Vos
url: https://www.vegdelicieus.nl
github_username: inktvis75
webmaster_verifications:
  google: google77c3a86c5835a59f.html
  bing: 977F45BDC399619C13FAEDC6CE5E184
locale: nl_NL

# Recipes
collections:
  recipes:
    output: true
    permalink: /:collection/:name
    layout: "recipe"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown settings
kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..3
  gfm_quirks: [paragraph_end]

# Sass
sass:
  sass_dir: css/_sass
  style: compact

# Mastodon
# mastodon-syndication:
# server: https://social.linux.pizza
